### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by DarjanKrijan** [gnu-octave/gnu-octave.github.io#1]
Hi,

I am a bit confused about the licensing of this repo as it's missing a `LICENSE` file. On the bottom of the octave.org page it says:

> This work is licensed under a [Creative Commons Attribution-NoDerivatives 4.0 International License](https://creativecommons.org/licenses/by-nd/4.0/)

What does that license apply to exactly? The resulting webpage with its design, text, images/graphics or also this repo with its workflow?

Would it be allowed to build a static webpage with a different theme with the workflow from this repo?

Regards,
Darjan Krijan

**Comment by siko1056** [comment]
Thank for the request @DarjanKrijan,

I hope https://github.com/gnu-octave/gnu-octave.github.io#license now explains the situation better.  I am no lawyer, please ask if something is still unclear :slightly_smiling_face: 

Any code can be used for whatever purpose, but the website content (the texts, etc.) is CC BY-ND 4.0 and should be cited as stated on the website.

**Comment by DarjanKrijan** [comment]
Thanks, this clears it up!
